### ISSUE TITLE
Calculator top distance problem

### ISSUE THREAD

**Issue by steilgedacht** [haydenull/logseq-woz-theme#10]
The 3 red dots of the calculator cover the first line:
![image](https://user-images.githubusercontent.com/89748204/196932225-d3de52d3-a1e4-453b-b710-778331cc1f7a.png)

```calc
3+3
4+4
```

**Comment by optimistic5** [comment]
In my case it looks like this
![image](https://user-images.githubusercontent.com/25054050/225330518-b157ddf7-88bd-41c6-b175-6f6683e9350e.png)
