### ISSUE TITLE
计算器显示有问题

### ISSUE THREAD

**Issue by artemith** [haydenull/logseq-woz-theme#11]
![image](https://github.com/haydenull/logseq-woz-theme/assets/14881525/c0910411-7816-4e83-b75e-a3618f6e5828)

Logseq: 0.9.10
Windows 10
Woz theme: 1.10.4

**Comment by haydenull** [comment]
1.10.5 版本应该修复了这个问题，可以再试试

**Comment by artemith** [comment]
的确修复了，感谢！
