### ISSUE TITLE
Display issue with "logseq-woz-theme" and "block calendar" plugin

### ISSUE THREAD

**Issue by rotavap** [haydenull/logseq-woz-theme#13]
Description:
I am experiencing a display issue with the "logseq-woz-theme" plugin in conjunction with the "block calendar" plugin in Logseq. Specifically, when I use the "logseq-woz-theme," the borders of the "block calendar" plugin are visible, whereas they are transparent when using other display themes such as "logseq-dev-theme." I have taken screenshots to illustrate the problem.

Screenshots:

    [Screenshot with ["logseq-woz-theme"] :
![calendar woz theme](https://github.com/haydenull/logseq-woz-theme/assets/75398664/34267429-b310-46ed-a588-1a8ec8028e77)

    [Screenshot with "logseq-dev-theme"]
![calendar dev theme](https://github.com/haydenull/logseq-woz-theme/assets/75398664/59226e96-7ea7-4c3e-bc1b-2e3e7958c2b9)

Steps to Reproduce:

-     Install Logseq version 0.9.8 on Linux Manjaro.
-     Install the "logseq-woz-theme" plugin.
-     Install the "block calendar" plugin.
-     Enable the "logseq-woz-theme" plugin.
-     Open Logseq and navigate to a page with the "block calendar" plugin.

Expected Behavior:
The borders of the "block calendar" plugin should be transparent, as observed with other display themes.

Actual Behavior:
The "logseq-woz-theme" displays visible borders around the "block calendar" plugin.

Additional Information:

-     Logseq version: 0.9.8
-     Operating System: Linux Manjaro

Please let me know if any further information is required to address this issue. Thank you!

**Comment by haydenull** [comment]
The reason for this issue is that woz-theme added border to table, while block-calendar uses table to draw the calendar.

In order to ensure the normal appearance of regular table styles, we believe that it would be more appropriate to handle this issue with block-calendar plugin.
