### ISSUE TITLE
下拉列表的渲染似乎有问题

### ISSUE THREAD

**Issue by willzhqiang** [haydenull/logseq-woz-theme#3]
下拉列表渲染似乎有问题，比如我有很多页面是Deep开头的，当我输入一些字母的时候，会自动和后面的字母隔开？
<img width="477" alt="image" src="https://user-images.githubusercontent.com/279170/170960555-fadefa8d-5135-442b-ab0b-b1f59f30c459.png">
比如下面这个主题用的是
https://github.com/sansui233/logseq-bonofix-theme
<img width="371" alt="image" src="https://user-images.githubusercontent.com/279170/170960929-3d8d90eb-108b-47c3-a326-721d96644a39.png">
似乎就没有这个问题。

**Comment by haydenull** [comment]
1.10.1 版本修复了这个问题
