### ISSUE TITLE
反馈两个样式冲突

### ISSUE THREAD

**Issue by Benyv0620** [haydenull/logseq-woz-theme#4]
1. 当高亮的内容包含双向链接时，会丢失透明度，导致无法阅读双向链接标题。
2. 使用advanced query时，会出现位置偏差。
<img width="422" alt="问题1" src="https://user-images.githubusercontent.com/47425245/171567446-1cdd6463-3503-4aaa-b443-1b2d88524cb6.png">
<img width="265" alt="问题2" src="https://user-images.githubusercontent.com/47425245/171567466-d5873fd2-eb4b-4075-b961-347bedd1c345.png">

**Comment by haydenull** [comment]
1. 第一个问题 1.10.1 版本已经修复
2. 第二个问题，应该是logseq故意这么设计的，文字需要和三角箭头对齐，所以就和圆点错位了
