### ISSUE TITLE
Headline indication

### ISSUE THREAD

**Issue by FM-Wiesbaden** [haydenull/logseq-woz-theme#5]
<img width="598" alt="CleanShot 2022-06-13 at 16 01 23@2x" src="https://user-images.githubusercontent.com/89744292/173371000-1e7fea05-111b-4ad1-b2e4-04bea8a8ace7.png">
Dear all,

I use your theme as standard theme.
Simple, clear - great stuff. Thank you.

One little issue (not sure if it's a bug or a feature).

Every heading (H1, H2, ...) shows the heading style after the heading text.

Example:
"This is a Heading 1 headline" h1
"This is a Heading 2 headline" h2

How can I get rid of the heading level indicators (h1 and h2 in the above examples)?

**Comment by haydenull** [comment]
Just add the following code to `custom.css`:

```css
.ls-block :is(h1, h2, h3, h4, h5)::after {
  display: none;
}
```
