### ISSUE TITLE
代码块的样式有异

### ISSUE THREAD

**Issue by Benyv0620** [haydenull/logseq-woz-theme#8]
代码块的样式有一块缺失的样子。
<img width="842" alt="截屏2022-07-14 19 16 52" src="https://user-images.githubusercontent.com/47425245/178970731-685f628a-0b69-4cb1-b3a3-a40b5fb552fc.png">

**Comment by haydenull** [comment]
请问你使用的 logseq 和 woz-theme 分别是什么版本呢

**Comment by Benyv0620** [comment]
logseq：版本0.7.6 (0.7.6)
Woz：V1.10.0。我升级到V1.10.3后，发现就没有该问题了。
已解决，多谢🙏。
