### ISSUE TITLE
夜间模式分隔线支持的似乎有问题

### ISSUE THREAD

**Issue by ethanchangit** [haydenull/logseq-woz-theme#9]
我的分隔线在夜间模式下就看不到了，希望大大可以改进一下，或者我本地出错了吗？
<img width="869" alt="image" src="https://user-images.githubusercontent.com/105411793/181253259-383afda9-1676-4ba2-880a-6744e9d14840.png">
<img width="869" alt="image" src="https://user-images.githubusercontent.com/105411793/181253183-12727088-0e6a-4a55-8cdb-fba28aeeebbf.png">
<img width="869" alt="image" src="https://user-images.githubusercontent.com/105411793/181253234-669a4d5a-7faa-41fd-8fba-2b611eba8513.png">

**Comment by haydenull** [comment]
1.10.5 版本应该修复了这个问题，可以再试试
